from typing import Any, Dict

CONFIG: Dict[str, Any] = {
    "lyrics": {
        "file": "lyrics.txt",
        "font_path": "Audiowide-Regular.ttf",
        "font_size": 0.472,
        "position": "top_center",
        "color": [255, 255, 255],
        "opacity": 1,
        "stroke_width": 0,
        "stroke_color": [0, 0, 0],
        "depth_composite": True,
        "transition_in": 0,
        "transition_out": 0,
        "animate_in": "fade",
        "animate_out": "fade",
        "max_duration": 4.0,
    },
    "transitions": {
        "types": ["zoom", "slide", "grid_wipe", "flash", "radial_wipe"],
        "types_weights": [0.3, 0.3, 0.15, 0.15, 0.1],
        "zoom_modes": ["in", "out"],
        "slide_directions": ["up", "down", "left", "right"],
        "duration": 0.2,
        "grid_wipe_cols": 6,
        "grid_wipe_rows": 4,
        "flash_color": [255, 255, 255],
    },
    "grid": {
        "col_weights": [1, 1, 1],
        "gap": 0.003,
        "color_grade_chances": {
            "desaturated": 0,
            "warm": 0.15,
            "cool": 0.15,
        },
        "desaturated_params": {"saturation": 0.0, "brightness": -10},
        "warm_params": {"saturation": 1.2, "brightness": 8, "contrast": 1.05},
        "cool_params": {"saturation": 0.8, "brightness": -8, "contrast": 1.1},
    },
    "span_weights": {
        "spans": [1, 2, 3],
        "weights": [0.6, 0.3, 0.1],
    },
    "beat_effects": {
        "grid": {
            "zoom": {"start_zoom": 1.03, "end_zoom": 1.0, "duration": 0.25},
            "zoom_to_point": {
                "chance": 0.3,
                "center": (0.5, 0.5),
                "start_zoom": 1.05,
                "end_zoom": 1.15,
                "duration": 0.35,
                "easing": "ease_in_out",
            },
            "ken_burns": {
                "chance": 0.0,
                "center": (0.35, 0.55),
                "zoom_out": 1.06,
                "zoom_in": 1.18,
                "drift_x": 0.015,
                "drift_y": 0.008,
                "duration": 0.8,
                "easing": "linear",
            },
            "panel_slide": {
                "chance": 0.4,
                "direction": "left",
                "start_offset": 1.0,
                "end_offset": 0.0,
                "duration": 0.3,
                "easing": "ease_out",
            },
            "panel_pulse": {
                "chance": 0.1,
                "start_scale": 1.0,
                "pulse_scale": 1.12,
                "end_scale": 1.0,
                "duration": 0.35,
                "easing": "ease_out",
            },
            "grid_scan": {
                "chance": 0.2,
                "num_bars": 240.0,
                "bar_speed": 0.8,
                "bar_width": 0.05,
                "duration": 0.3,
                "easing": "linear",
            },
            "grid_flash": {
                "chance": 0.3,
                "intensity": 0.4,
                "duration": 0.2,
                "easing": "linear",
            },
            "grid_glitch": {
                "chance": 0.4,
                "intensity": 0.8,
                "duration": 0.25,
                "easing": "linear",
            },
            "grid_wave": {
                "chance": 0.2,
                "frequency": 20.0,
                "amplitude": 0.03,
                "speed": 5.0,
                "duration": 0.35,
                "easing": "linear",
            },
            "grid_pixelate": {
                "chance": 0.2,
                "max_pixels": 400.0,
                "min_pixels": 25.0,
                "duration": 0.3,
                "easing": "linear",
            },
            "grid_chromatic": {
                "chance": 0.2,
                "intensity": 1.0,
                "angle": 0.0,
                "duration": 0.3,
                "easing": "linear",
            },
            "panel_bounce": {
                "chance": 0.35,
                "direction": "up",
                "amplitude": 0.06,
                "duration": 0.2,
                "easing": "ease_out",
            },
            "panel_spin": {
                "chance": 0.25,
                "max_angle": 3.0,
                "duration": 0.25,
                "easing": "ease_out",
            },
            "rgb_shift": {
                "chance": 0.7,
                "start_shift": 0.083,
                "end_shift": 0.0,
                "duration": 0.2,
            },
            "yolo_emission": {
                "chance": 0.15,
                "inner_color": [180, 220, 255],
                "outer_color": [30, 80, 255],
                "inner_radius": 0.042,
                "outer_radius": 0.142,
                "intensity": 0.8,
                "pulse_speed": 2.5,
                "pulse_amplitude": 0.15,
                "duration": 0.6,
                "easing": "ease_in_out",
            },
        },
        "cc": {
            "zoom": {"start_zoom": 1.03, "end_zoom": 1.0, "duration": 0.25},
            "zoom_to_point": {
                "chance": 0.0,
                "center": (0.5, 0.5),
                "start_zoom": 1.0,
                "end_zoom": 1.6,
                "duration": 0.4,
                "easing": "ease_in_out",
            },
            "ken_burns": {
                "chance": 0.0,
                "center": (0.5, 0.5),
                "zoom_out": 1.04,
                "zoom_in": 1.16,
                "drift_x": 0.01,
                "drift_y": 0.01,
                "duration": 0.7,
                "easing": "linear",
            },
            "yolo_emission": {
                "chance": 0.15,
                "inner_color": [180, 220, 255],
                "outer_color": [30, 80, 255],
                "inner_radius": 0.042,
                "outer_radius": 0.142,
                "intensity": 0.8,
                "pulse_speed": 2.5,
                "pulse_amplitude": 0.15,
                "duration": 0.6,
                "easing": "ease_in_out",
            },
            "rgb_shift": {
                "chance": 0.5,
                "start_shift": 0.111,
                "end_shift": 0.0,
                "duration": 0.2,
            },
        },
        "dtw": {
            "zoom": {"start_zoom": 1, "end_zoom": 1.05, "duration": 0.25},
            "zoom_to_point": {
                "chance": 0.0,
                "center": (0.5, 0.5),
                "start_zoom": 1.0,
                "end_zoom": 1.8,
                "duration": 0.45,
                "easing": "ease_in_out",
            },
            "ken_burns": {
                "chance": 0.0,
                "center": (0.5, 0.5),
                "zoom_out": 1.05,
                "zoom_in": 1.2,
                "drift_x": 0.02,
                "drift_y": 0.015,
                "duration": 0.9,
                "easing": "linear",
            },
            "yolo_emission": {
                "chance": 0.25,
                "inner_color": [180, 220, 255],
                "outer_color": [30, 80, 255],
                "inner_radius": 0.042,
                "outer_radius": 0.142,
                "intensity": 0.8,
                "pulse_speed": 2.5,
                "pulse_amplitude": 0.15,
                "duration": 0.6,
                "easing": "ease_in_out",
            },
            "rgb_shift": {
                "chance": 0.7,
                "start_shift": 0.069,
                "end_shift": 0.0,
                "duration": 0.2,
            },
        },
        "single": {
            "zoom": {"start_zoom": 1.1, "end_zoom": 1.0, "duration": 0.3},
            "zoom_to_point": {
                "chance": 0.1,
                "center": (0.5, 0.5),
                "start_zoom": 1.0,
                "end_zoom": 1.5,
                "duration": 0.35,
                "easing": "ease_in_out",
            },
            "ken_burns": {
                "chance": 0.1,
                "center": (0.5, 0.5),
                "zoom_out": 1.04,
                "zoom_in": 1.15,
                "drift_x": 0.012,
                "drift_y": 0.008,
                "duration": 0.6,
                "easing": "linear",
            },
            "yolo_emission": {
                "chance": 0.15,
                "inner_color": [180, 220, 255],
                "outer_color": [30, 80, 255],
                "inner_radius": 0.042,
                "outer_radius": 0.142,
                "intensity": 0.8,
                "pulse_speed": 2.5,
                "pulse_amplitude": 0.15,
                "duration": 0.6,
                "easing": "ease_in_out",
            },
        },
    },
}
