[package]
name = "ocv-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
rayon.workspace = true
image.workspace = true
imageproc.workspace = true
fast_image_resize.workspace = true
ab_glyph.workspace = true
tempfile.workspace = true
ort = { version = "2.0.0-rc.12", default-features = false, features = ["load-dynamic", "ndarray", "std", "api-24"] }
ndarray = "0.17"
animato.workspace = true

[dev-dependencies]
